name: Build, Migrate Database, and Deploy ASP.Net Core app

env:
  AZURE_WEBAPP_NAME: street-sweeping-reminder      # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'                   # path inside the artifact to deploy (usually '.')
  API_PROJECT_PATH: 'StreetSweepingReminder.Api/StreetSweepingReminder.Api.csproj' # Correct relative path to API project
  DOTNET_VERSION: '9.0'              # Specific preview version

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore ${{ env.API_PROJECT_PATH }}

      - name: Build project
        run: dotnet build ${{ env.API_PROJECT_PATH }} --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish ${{ env.API_PROJECT_PATH }} --configuration Release --no-build -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}